spring:
  application:
    name: mapuescuela
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mapuescuela}
    username: ${SPRING_DATASOURCE_USERNAME:mapuescuela}
    password: ${SPRING_DATASOURCE_PASSWORD:mapuescuela_dev}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

flowable:
  database-schema-update: true
  async-executor-activate: true

server:
  port: ${PORT:8080}
